//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRDM4ATMsWin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class appRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal appRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RRDM4ATMsWin.appRes", typeof(appRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIST OF NOT REPLENISHED YET.
        /// </summary>
        internal static string Form22MISlabel14a {
            get {
                return ResourceManager.GetString("Form22MISlabel14a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIST OF REPLENISHED BY USER PERFORMANCE.
        /// </summary>
        internal static string Form22MISlabel14b {
            get {
                return ResourceManager.GetString("Form22MISlabel14b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIST WITH ABOVE AVERAGE REPL TIME.
        /// </summary>
        internal static string Form22MISlabel14c {
            get {
                return ResourceManager.GetString("Form22MISlabel14c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid User Number .
        /// </summary>
        internal static string Form40MSG001 {
            get {
                return ResourceManager.GetString("Form40MSG001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found!.
        /// </summary>
        internal static string Form40MSG002 {
            get {
                return ResourceManager.GetString("Form40MSG002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Password!.
        /// </summary>
        internal static string Form40MSG003 {
            get {
                return ResourceManager.GetString("Form40MSG003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print all.
        /// </summary>
        internal static string Form62button1 {
            get {
                return ResourceManager.GetString("Form62button1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Chosen Tran.
        /// </summary>
        internal static string Form62button2 {
            get {
                return ResourceManager.GetString("Form62button2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video clip.
        /// </summary>
        internal static string Form62button3 {
            get {
                return ResourceManager.GetString("Form62button3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal For Chosen.
        /// </summary>
        internal static string Form62button4 {
            get {
                return ResourceManager.GetString("Form62button4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal For Repl.Cycle.
        /// </summary>
        internal static string Form62button5 {
            get {
                return ResourceManager.GetString("Form62button5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tran No.
        /// </summary>
        internal static string Form62Grd1Cl0 {
            get {
                return ResourceManager.GetString("Form62Grd1Cl0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIST OF TRANSACTIONS .
        /// </summary>
        internal static string Form62label14 {
            get {
                return ResourceManager.GetString("Form62label14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for Repl. Cycle: .
        /// </summary>
        internal static string Form62label1a {
            get {
                return ResourceManager.GetString("Form62label1a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for period : .
        /// </summary>
        internal static string Form62label1b {
            get {
                return ResourceManager.GetString("Form62label1b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for Card.
        /// </summary>
        internal static string Form62label1c {
            get {
                return ResourceManager.GetString("Form62label1c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for account.
        /// </summary>
        internal static string Form62label1d {
            get {
                return ResourceManager.GetString("Form62label1d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for trace number.
        /// </summary>
        internal static string Form62label1e {
            get {
                return ResourceManager.GetString("Form62label1e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line No.
        /// </summary>
        internal static string Form67Grd1Cl0 {
            get {
                return ResourceManager.GetString("Form67Grd1Cl0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Description .
        /// </summary>
        internal static string Form67Grd1Cl01 {
            get {
                return ResourceManager.GetString("Form67Grd1Cl01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity .
        /// </summary>
        internal static string Form67Grd1Cl02 {
            get {
                return ResourceManager.GetString("Form67Grd1Cl02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATM JOURNAL FOR TRACE:.
        /// </summary>
        internal static string Form67label14a {
            get {
                return ResourceManager.GetString("Form67label14a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATM JOURNAL FOR REPL. CYCLE:.
        /// </summary>
        internal static string Form67label14b {
            get {
                return ResourceManager.GetString("Form67label14b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please login to the system..
        /// </summary>
        internal static string LoginInstruction {
            get {
                return ResourceManager.GetString("LoginInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASSWORD.
        /// </summary>
        internal static string PasswordCapital {
            get {
                return ResourceManager.GetString("PasswordCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USER ID.
        /// </summary>
        internal static string UserIdCapital {
            get {
                return ResourceManager.GetString("UserIdCapital", resourceCulture);
            }
        }
    }
}
