USE [ReportServer]
GO

SELECT [ItemID]
      ,[Path]
      ,[Name]
      ,[ParentID]
      ,[Type]
      ,[Content]
      ,[Intermediate]
      ,[SnapshotDataID]
      ,[LinkSourceID]
      ,[Property]
      ,[Description]
      ,[Hidden]
      ,[CreatedByID]
      ,[CreationDate]
      ,[ModifiedByID]
      ,[ModifiedDate]
      ,[MimeType]
      ,[SnapshotLimit]
      ,[Parameter]
      ,[PolicyID]
      ,[PolicyRoot]
      ,[ExecutionFlag]
      ,[ExecutionTime]
      ,[SubType]
      ,[ComponentID]
  FROM [dbo].[Catalog]
GO

